### Day by day trading - 2019-01-09

#### Pseudocode

In [1]:
# Import standard libraries
%matplotlib inline

import pandas as pd
import numpy as np
import datetime
from dateutil.relativedelta import relativedelta
import matplotlib.pylab as plt
from pandas.tseries.offsets import BDay
import os
import os.path
import pickle
import random
import json
from scipy import stats
from datetime import datetime

from sklearn.model_selection import StratifiedShuffleSplit, TimeSeriesSplit
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [2]:
# Import custom libraries
from Code.lib.plot_utils import PlotUtility
from Code.lib.time_utils import TimeUtility
from Code.lib.retrieve_data import DataRetrieve, ComputeTarget
from Code.lib.candle_indicators import CandleIndicators
from Code.lib.transformers import Transformers
from Code.lib.ta_momentum_studies import TALibMomentumStudies
from Code.lib.model_utils import ModelUtility, TimeSeriesSplitImproved
from Code.lib.feature_generator import FeatureGenerator
from Code.utilities.stat_tests import stationarity_tests
from Code.lib.config import current_feature, feature_dict
from Code.models import models_utils
from Code.lib.model_algos import AlgoUtility

plotIt = PlotUtility()
timeUtil = TimeUtility()
ct = ComputeTarget()
candle_ind = CandleIndicators()
dSet = DataRetrieve()
taLibMomSt = TALibMomentumStudies()
transf = Transformers()
modelUtil = ModelUtility()
featureGen = FeatureGenerator()
dSet = DataRetrieve()
modelAlgo = AlgoUtility()

In [3]:
# function to create system directory based on system name if one doesn't already exist
def get_system_dir(system_name):
    # Create system directory in current path
    current_directory = os.getcwd()
    system_directory = os.path.join(current_directory, system_name)
    if not os.path.exists(system_directory):
       os.makedirs(system_directory)
    return system_directory

In [4]:
# functions for save and load json files
def save_json(filename, json_file):
    # Save system_dict to file
    #filename = 'system_dict.json'
    file_path = os.path.join(system_directory, filename)
    with open(file_path, 'w') as fp:
        json.dump(json_file, fp, sort_keys=True, indent=4)
        
def load_json(file_path):
    with open(file_path, 'r') as fp:
        json_file = json.load(fp)
    return json_file

### Get system info

In [5]:
system_name = "TLT-Long-system-7045-V1"

In [6]:
# Get system info
current_directory = os.getcwd()
system_directory = os.path.join(current_directory, system_name)
if not os.path.exists(system_directory):
    print("system doesn't exist")
else:
    filename = 'system_dict.json'    
    file_path = os.path.join(system_directory, filename)
    system_dict = load_json(file_path)
    issue = system_dict["issue"]
    direction = system_dict["direction"]
    ver_num = system_dict["ver_num"]
    # Perhaps only load these when needed?
    pivotDate = system_dict["pivot_date"]
    is_oos_ratio = system_dict["is_oos_ratio"]
    oos_months = system_dict["oos_months"]
    segments = system_dict["segments"]

In [7]:
# Set IS-OOS parameters
from datetime import datetime
pivotDate = datetime.strptime(pivotDate, '%Y-%m-%d')
print(pivotDate)
pivotDate = datetime.date(pivotDate)

# set date splits
isOosDates = timeUtil.is_oos_data_split(issue, pivotDate, is_oos_ratio, oos_months, segments)
dataLoadStartDate = isOosDates[0]
is_start_date = isOosDates[1]
oos_start_date = isOosDates[2]
is_months = isOosDates[3]
is_end_date = isOosDates[4]
oos_end_date = isOosDates[5]

modelStartDate = oos_start_date

2019-01-08 00:00:00
                    Segments:  1
                IS OOS Ratio:  4
                  OOS months:  4
                   IS Months:  16
              Months to load:  20
              Data Load Date:  2017-04-08
              IS Start  Date:  2017-05-08
              OOS Start Date:  2018-09-08
                  Pivot Date:  2019-01-08

### Set trade date
In this case, increment to next business day after pivotDate

Do it manually for now

In [8]:
from datetime import timedelta
from pandas.tseries.offsets import BDay
tradeDate = pivotDate + BDay(1)
print(tradeDate)

2019-01-09 00:00:00

### Retrieve feature_dict

In [9]:
file_name = 'feature_dict.json'
file_path = os.path.join(system_directory, file_name)
feature_dict = load_json(file_path)

### Day by day procedure
1. Set trade date
2. Update close, transform
3. Retrieve model
4. Make prediction
5. Update prev day gainAhead, trade (using TRADE DECISION), Equity (what df?)
6. Update shadow trades df from (5)
7. Calculate safe-f, CAR25 (TMS-Part 1)
8. TRADE DECISION
9. Update pivot date in dict

### Steps to walkthrough
1. Make copy of raw data and truncate it to pretend existing date

In [10]:
raw_df = dSet.read_issue_data(issue)

Successfully retrieved data series for TLT

In [11]:
raw_df.tail(35)

            Date    Open      High       Low     Close  AdjClose      Volume
4133  2018-12-26  120.99  121.3900  119.9700  120.0200  119.7479  11700412.0
4134  2018-12-27  121.26  121.3800  119.9800  120.0400  119.7679  12146772.0
4135  2018-12-28  120.40  121.0500  120.2900  121.0500  120.7756   9879116.0
4136  2018-12-31  120.65  121.5600  120.4600  121.5100  121.2345  17408971.0
4137  2019-01-02  121.66  122.1600  121.3401  122.1500  121.8731  19841527.0
4138  2019-01-03  122.29  123.8600  122.2267  123.5400  123.2599  21187045.0
4139  2019-01-04  122.34  122.5600  121.6500  122.1100  121.8332  12970226.0
4140  2019-01-07  122.62  122.6500  121.6200  121.7500  121.4740   8498104.0
4141  2019-01-08  121.69  121.9400  121.3900  121.4300  121.1547   7737103.0
4142  2019-01-09  121.26  121.4300  120.7950  121.2400  120.9651   9349245.0
4143  2019-01-10  121.28  121.4100  120.3400  120.4600  120.1869   8222860.0
4144  2019-01-11  120.83  121.2700  120.6800  120.9300  120.6558   5786934.0
4145  2019-01-14  120.90  121.0100  120.2416  120.4800  120.2069   6730681.0
4146  2019-01-15  120.56  120.5700  119.9500  120.0400  119.7679   8997352.0
4147  2019-01-16  119.59  120.3900  119.5100  120.1600  119.8876   6048446.0
4148  2019-01-17  120.22  120.5300  119.8900  120.1900  119.9175   8153350.0
4149  2019-01-18  119.84  120.1200  119.3850  119.5600  119.2890  14106447.0
4150  2019-01-22  120.31  120.7200  120.0700  120.3700  120.0971   8881133.0
4151  2019-01-23  119.88  120.6200  119.8300  120.3200  120.0472   5776907.0
4152  2019-01-24  120.91  121.2600  120.7100  121.1100  120.8354   7121480.0
4153  2019-01-25  120.59  120.7500  120.3200  120.5300  120.2568   6460820.0
4154  2019-01-28  120.54  120.9400  120.4100  120.4100  120.1370   6435820.0
4155  2019-01-29  120.53  121.0400  120.3900  121.0200  120.7456   5750177.0
4156  2019-01-30  120.84  120.9800  120.3300  120.9300  120.6558  10571325.0
4157  2019-01-31  121.55  122.1800  121.5000  121.9700  121.6935  11843413.0
4158  2019-02-01  121.48  121.5700  120.8446  120.9600  120.9600  12024576.0
4159  2019-02-04  120.44  120.5500  120.0200  120.4200  120.4200   8966375.0
4160  2019-02-05  120.73  121.2300  120.6600  120.9700  120.9700   6983255.0
4161  2019-02-06  121.36  121.4100  120.7300  121.0300  121.0300   5184018.0
4162  2019-02-07  121.46  121.9100  121.2300  121.8300  121.8300   8781040.0
4163  2019-02-08  122.26  122.4700  122.0700  122.3500  122.3500   5885427.0
4164  2019-02-11  121.86  122.1800  121.7500  121.8700  121.8700   4353004.0
4165  2019-02-12  121.66  121.7500  121.2000  121.5550  121.5550   7939591.0
4166  2019-02-13  121.15  121.3900  120.9100  121.1000  121.1000   4757681.0
4167  2019-02-14  122.14  122.1957  121.6500  121.7633  121.7633   2496779.0

#### Trim df to 2019-01-08, then add 2019-01-09
Don't use set_date_range to update to new date data

In [12]:
tradeDate = tradeDate.strftime('%Y-%m-%d')
tradeDate

'2019-01-09'

In [13]:
# Use trade date instead of hard coding date
trimmed_df = raw_df.iloc[0:raw_df[raw_df.Date == tradeDate].index[0]]
trimmed_df.tail(2)

            Date    Open    High     Low   Close  AdjClose     Volume
4140  2019-01-07  122.62  122.65  121.62  121.75  121.4740  8498104.0
4141  2019-01-08  121.69  121.94  121.39  121.43  121.1547  7737103.0

In [14]:
# add 2019-01-08
new_data_df = trimmed_df.append({'Date' : tradeDate , 'Open' : 121.26, 'High' : 121.43, 'Low' : 120.80, 'Close' : 121.24, 'AdjClose' : 120.97, 'Volume' : 9349245.0 } , ignore_index=True)
new_data_df.tail(2)

            Date    Open    High     Low   Close  AdjClose     Volume
4141  2019-01-08  121.69  121.94  121.39  121.43  121.1547  7737103.0
4142  2019-01-09  121.26  121.43  120.80  121.24  120.9700  9349245.0

In [15]:
# get first row
df_start_date = new_data_df.Date[0]
df_start_date

'2002-07-26'

In [16]:
# get last row
lastRow = new_data_df.shape[0]
df_end_date = new_data_df.Date[lastRow-1]
df_end_date

'2019-01-09'

In [17]:
feat_df = dSet.set_date_range(new_data_df, df_start_date, df_end_date)
# Resolve any NA's for now
feat_df.fillna(method='ffill', inplace=True)

#set beLong level
beLongThreshold = 0.000
feat_df = ct.setTarget(new_data_df, "Long", beLongThreshold)

In [18]:
feat_df.tail(2)

,Open,High,Low,Close,AdjClose,Volume,gainAhead,beLong
Date,,,,,,,,
2019-01-08,121.69,121.94,121.39,121.43,121.1547,7737103.0,-0.001565,-1
2019-01-09,121.26,121.43,120.80,121.24,120.9700,9349245.0,0.000000,-1

#### Adding features with new day
Should I be generating new features again?
How would add just one day's worth?

In [19]:
file_name = 'input_dict.json'
file_path = os.path.join(system_directory, file_name)
input_dict = load_json(file_path)

In [20]:
feat_df = featureGen.generate_features(feat_df, input_dict)

f1
fname:  PPO
params:  [2, 5]
Current feature:  PPO_f2_s5
transform:  ['Normalized', 20]
pass params [20]
f10
fname:  kaufman_AMA
params:  [4]
Current feature:  KAMA_4
transform:  ['Normalized', 20]
pass params [20]
f2
fname:  RSI
params:  [2]
Current feature:  RSI_2
transform:  ['Normalized', 20]
pass params [20]
f3
fname:  CMO
params:  [5]
Current feature:  CMO_5
transform:  ['Normalized', 20]
pass params [20]
f4
fname:  CCI
params:  [10]
Current feature:  CCI_10
transform:  ['Normalized', 20]
pass params [20]
f5
fname:  UltimateOscillator
params:  [10, 20, 30]
Current feature:  UltOsc_t110_t220_t330
transform:  ['Normalized', 20]
pass params [20]
f6
fname:  ROC
params:  [10]
Current feature:  ROC_10
transform:  ['Normalized', 20]
pass params [20]
f7
fname:  Lag
params:  ['Close', 3]
Date
2018-12-11    118.48
2018-12-12    119.17
2018-12-13    119.60
2018-12-14    121.18
2018-12-17    120.74
2018-12-18    120.72
2018-12-19    121.32
2018-12-20    120.02
2018-12-21    120.04
2018-12-24    121.05
2018-12-26    121.51
2018-12-27    122.15
2018-12-28    123.54
2018-12-31    122.11
2019-01-02    121.75
2019-01-03    121.43
2019-01-04    121.24
2019-01-07       NaN
2019-01-08       NaN
2019-01-09       NaN
Name: Close_lag3, dtype: float64
===============
              Open     High       Low   Close  AdjClose      Volume  \
Date
2018-12-11  118.97  119.380  118.6100  118.88  118.3316   8071952.0
2018-12-12  118.58  118.720  118.2400  118.35  117.8040   6182206.0
2018-12-13  118.46  118.580  117.9800  118.07  117.5253   5564328.0
2018-12-14  118.55  118.770  118.2200  118.48  117.9334   8169221.0
2018-12-17  118.59  119.300  118.5800  119.17  118.6203   9726781.0
2018-12-18  119.07  119.785  118.9400  119.60  119.3289  10019103.0
2018-12-19  120.11  121.660  119.9200  121.18  120.9053  23046272.0
2018-12-20  122.01  122.030  120.6700  120.74  120.4663  18543731.0
2018-12-21  121.14  121.210  120.3900  120.72  120.4463   9945103.0
2018-12-24  121.13  121.420  120.9100  121.32  121.0450   8377482.0
2018-12-26  120.99  121.390  119.9700  120.02  119.7479  11700412.0
2018-12-27  121.26  121.380  119.9800  120.04  119.7679  12146772.0
2018-12-28  120.40  121.050  120.2900  121.05  120.7756   9879116.0
2018-12-31  120.65  121.560  120.4600  121.51  121.2345  17408971.0
2019-01-02  121.66  122.160  121.3401  122.15  121.8731  19841527.0
2019-01-03  122.29  123.860  122.2267  123.54  123.2599  21187045.0
2019-01-04  122.34  122.560  121.6500  122.11  121.8332  12970226.0
2019-01-07  122.62  122.650  121.6200  121.75  121.4740   8498104.0
2019-01-08  121.69  121.940  121.3900  121.43  121.1547   7737103.0
2019-01-09  121.26  121.430  120.8000  121.24  120.9700   9349245.0

            gainAhead  beLong  PPO_f2_s5  PPO_f2_s5_Normalized     ...      \
Date                                                               ...
2018-12-11  -0.004458      -1   0.379939              0.540122     ...
2018-12-12  -0.002366      -1   0.058205              0.276064     ...
2018-12-13   0.003473       1  -0.263242              0.082817     ...
2018-12-14   0.005824       1  -0.220186              0.133998     ...
2018-12-17   0.003608       1   0.198162              0.527399     ...
2018-12-18   0.013211       1   0.548284              0.788655     ...
2018-12-19  -0.003631      -1   0.913663              0.925300     ...
2018-12-20  -0.000166      -1   0.939633              0.881740     ...
2018-12-21   0.004970       1   0.372458              0.579401     ...
2018-12-24  -0.010715      -1   0.255153              0.484440     ...
2018-12-26   0.000167       1  -0.104308              0.294287     ...
2018-12-27   0.008414       1  -0.446221              0.177998     ...
2018-12-28   0.003800       1  -0.070463              0.327940     ...
2018-12-31   0.005267       1   0.407325              0.545069     ...
2019-01-02   0.011379       1   0.724242              0.685333     ...
2019-01-03  -0.011575      -1   0.975686              0.782509     ...
2019-01-04  -0.002948      -1   0.616849              0.598571     ...
2019-01-07  -0.002628      -1  -0.230747              0.201166     ...
2019-01-08  -0.001565      -1  -0.495925              0.131362     ...
2019-01-09   0.000000      -1  -0.556494              0.128818     ...

            RSI_2_Normalized      CMO_5  CMO_5_Normalized      CCI_10  \
Date
2018-12-11          0.592531  85.377167          0.885627   87.029206
2018-12-12          0.000662  41.807605          0.322333   55.475623
2018-12-13          0.005597  22.754849          0.151269   37.886877
2018-12-14          0.234772  38.001524          0.287364   45.743343
2018-12-17          0.511067  56.191660          0.487936   86.525999
2018-12-18          0.542409  64.341474          0.580507  145.794603
2018-12-19          0.600225  80.771432          0.742961  246.310526
2018-12-20          0.297395  55.784996          0.470911  164.570274
2018-12-21          0.317155  54.571076          0.486982   98.115636
2018-12-24          0.534919  64.844020          0.583670   95.802545
2018-12-26          0.046989   2.232561          0.109244   39.605270
2018-12-27          0.051710   2.941503          0.112330   30.792787
2018-12-28          0.431510  33.418471          0.317661   45.117207
2018-12-31          0.519009  43.515902          0.391798   76.131687
2019-01-02          0.587962  55.304304          0.496599  159.695601
2019-01-03          0.638427  71.469548          0.654559  247.935936
2019-01-04          0.071162  17.035946          0.163465   80.859687
2019-01-07          0.077053   6.406187          0.091718   55.793516
2019-01-08          0.144010  -3.347621          0.051502    9.564517
2019-01-09          0.180108  -9.504332          0.087375  -32.486754

            CCI_10_Normalized  UltOsc_t110_t220_t330  \
Date
2018-12-11           0.319235              60.270912
2018-12-12           0.037530              58.164945
2018-12-13           0.030615              57.638061
2018-12-14           0.165710              57.697005
2018-12-17           0.425549              58.769197
2018-12-18           0.793278              57.298522
2018-12-19           0.988591              58.014084
2018-12-20           0.805082              55.214977
2018-12-21           0.507342              52.179578
2018-12-24           0.476473              54.327715
2018-12-26           0.253822              49.691011
2018-12-27           0.225541              46.183860
2018-12-28           0.293985              51.121298
2018-12-31           0.412609              54.050944
2019-01-02           0.764951              55.153356
2019-01-03           0.941671              56.302881
2019-01-04           0.440680              49.835856
2019-01-07           0.355621              50.677604
2019-01-08           0.127996              48.878625
2019-01-09           0.051473              48.520088

            UltOsc_t110_t220_t330_Normalized    ROC_10  ROC_10_Normalized  \
Date
2018-12-11                          0.676619  3.481894           0.884760
2018-12-12                          0.543576  2.904095           0.739157
2018-12-13                          0.515265  3.162953           0.700185
2018-12-14                          0.520287  3.115753           0.672196
2018-12-17                          0.619991  3.329576           0.702885
2018-12-18                          0.443912  3.210217           0.683267
2018-12-19                          0.563118  2.851808           0.594393
2018-12-20                          0.106359  2.157543           0.409397
2018-12-21                          0.012860  1.950849           0.366215
2018-12-24                          0.157539  2.035324           0.383694
2018-12-26                          0.012623  0.958950           0.188563
2018-12-27                          0.005091  1.427968           0.284868
2018-12-28                          0.119531  2.523926           0.487989
2018-12-31                          0.261242  2.557394           0.480257
2019-01-02                          0.303317  2.500629           0.450596
2019-01-03                          0.385714  3.294314           0.743794
2019-01-04                          0.031756  0.767453           0.006328
2019-01-07                          0.085309  0.836508           0.031397
2019-01-08                          0.131111  0.588138           0.034103
2019-01-09                          0.162324 -0.065941           0.027165

            Close_lag3
Date
2018-12-11  118.480000
2018-12-12  119.170000
2018-12-13  119.600000
2018-12-14  121.180000
2018-12-17  120.740000
2018-12-18  120.720000
2018-12-19  121.320000
2018-12-20  120.020000
2018-12-21  120.040000
2018-12-24  121.050000
2018-12-26  121.510000
2018-12-27  122.150000
2018-12-28  123.540000
2018-12-31  122.110000
2019-01-02  121.750000
2019-01-03  121.430000
2019-01-04  121.240000
2019-01-07  121.473333
2019-01-08  121.335000
2019-01-09  121.240000

[20 rows x 23 columns]
Current feature:  Close_lag3
transform:  ['Normalized', 20]
pass params [20]

f8
fname:  Lag
params:  ['Close', 5]
Date
2018-12-11    119.60
2018-12-12    121.18
2018-12-13    120.74
2018-12-14    120.72
2018-12-17    121.32
2018-12-18    120.02
2018-12-19    120.04
2018-12-20    121.05
2018-12-21    121.51
2018-12-24    122.15
2018-12-26    123.54
2018-12-27    122.11
2018-12-28    121.75
2018-12-31    121.43
2019-01-02    121.24
2019-01-03       NaN
2019-01-04       NaN
2019-01-07       NaN
2019-01-08       NaN
2019-01-09       NaN
Name: Close_lag5, dtype: float64
===============
              Open     High       Low   Close  AdjClose      Volume  \
Date
2018-12-11  118.97  119.380  118.6100  118.88  118.3316   8071952.0
2018-12-12  118.58  118.720  118.2400  118.35  117.8040   6182206.0
2018-12-13  118.46  118.580  117.9800  118.07  117.5253   5564328.0
2018-12-14  118.55  118.770  118.2200  118.48  117.9334   8169221.0
2018-12-17  118.59  119.300  118.5800  119.17  118.6203   9726781.0
2018-12-18  119.07  119.785  118.9400  119.60  119.3289  10019103.0
2018-12-19  120.11  121.660  119.9200  121.18  120.9053  23046272.0
2018-12-20  122.01  122.030  120.6700  120.74  120.4663  18543731.0
2018-12-21  121.14  121.210  120.3900  120.72  120.4463   9945103.0
2018-12-24  121.13  121.420  120.9100  121.32  121.0450   8377482.0
2018-12-26  120.99  121.390  119.9700  120.02  119.7479  11700412.0
2018-12-27  121.26  121.380  119.9800  120.04  119.7679  12146772.0
2018-12-28  120.40  121.050  120.2900  121.05  120.7756   9879116.0
2018-12-31  120.65  121.560  120.4600  121.51  121.2345  17408971.0
2019-01-02  121.66  122.160  121.3401  122.15  121.8731  19841527.0
2019-01-03  122.29  123.860  122.2267  123.54  123.2599  21187045.0
2019-01-04  122.34  122.560  121.6500  122.11  121.8332  12970226.0
2019-01-07  122.62  122.650  121.6200  121.75  121.4740   8498104.0
2019-01-08  121.69  121.940  121.3900  121.43  121.1547   7737103.0
2019-01-09  121.26  121.430  120.8000  121.24  120.9700   9349245.0

            gainAhead  beLong  PPO_f2_s5  PPO_f2_s5_Normalized     ...      \
Date                                                               ...
2018-12-11  -0.004458      -1   0.379939              0.540122     ...
2018-12-12  -0.002366      -1   0.058205              0.276064     ...
2018-12-13   0.003473       1  -0.263242              0.082817     ...
2018-12-14   0.005824       1  -0.220186              0.133998     ...
2018-12-17   0.003608       1   0.198162              0.527399     ...
2018-12-18   0.013211       1   0.548284              0.788655     ...
2018-12-19  -0.003631      -1   0.913663              0.925300     ...
2018-12-20  -0.000166      -1   0.939633              0.881740     ...
2018-12-21   0.004970       1   0.372458              0.579401     ...
2018-12-24  -0.010715      -1   0.255153              0.484440     ...
2018-12-26   0.000167       1  -0.104308              0.294287     ...
2018-12-27   0.008414       1  -0.446221              0.177998     ...
2018-12-28   0.003800       1  -0.070463              0.327940     ...
2018-12-31   0.005267       1   0.407325              0.545069     ...
2019-01-02   0.011379       1   0.724242              0.685333     ...
2019-01-03  -0.011575      -1   0.975686              0.782509     ...
2019-01-04  -0.002948      -1   0.616849              0.598571     ...
2019-01-07  -0.002628      -1  -0.230747              0.201166     ...
2019-01-08  -0.001565      -1  -0.495925              0.131362     ...
2019-01-09   0.000000      -1  -0.556494              0.128818     ...

            CMO_5_Normalized      CCI_10  CCI_10_Normalized  \
Date
2018-12-11          0.885627   87.029206           0.319235
2018-12-12          0.322333   55.475623           0.037530
2018-12-13          0.151269   37.886877           0.030615
2018-12-14          0.287364   45.743343           0.165710
2018-12-17          0.487936   86.525999           0.425549
2018-12-18          0.580507  145.794603           0.793278
2018-12-19          0.742961  246.310526           0.988591
2018-12-20          0.470911  164.570274           0.805082
2018-12-21          0.486982   98.115636           0.507342
2018-12-24          0.583670   95.802545           0.476473
2018-12-26          0.109244   39.605270           0.253822
2018-12-27          0.112330   30.792787           0.225541
2018-12-28          0.317661   45.117207           0.293985
2018-12-31          0.391798   76.131687           0.412609
2019-01-02          0.496599  159.695601           0.764951
2019-01-03          0.654559  247.935936           0.941671
2019-01-04          0.163465   80.859687           0.440680
2019-01-07          0.091718   55.793516           0.355621
2019-01-08          0.051502    9.564517           0.127996
2019-01-09          0.087375  -32.486754           0.051473

            UltOsc_t110_t220_t330  UltOsc_t110_t220_t330_Normalized    ROC_10  \
Date
2018-12-11              60.270912                          0.676619  3.481894
2018-12-12              58.164945                          0.543576  2.904095
2018-12-13              57.638061                          0.515265  3.162953
2018-12-14              57.697005                          0.520287  3.115753
2018-12-17              58.769197                          0.619991  3.329576
2018-12-18              57.298522                          0.443912  3.210217
2018-12-19              58.014084                          0.563118  2.851808
2018-12-20              55.214977                          0.106359  2.157543
2018-12-21              52.179578                          0.012860  1.950849
2018-12-24              54.327715                          0.157539  2.035324
2018-12-26              49.691011                          0.012623  0.958950
2018-12-27              46.183860                          0.005091  1.427968
2018-12-28              51.121298                          0.119531  2.523926
2018-12-31              54.050944                          0.261242  2.557394
2019-01-02              55.153356                          0.303317  2.500629
2019-01-03              56.302881                          0.385714  3.294314
2019-01-04              49.835856                          0.031756  0.767453
2019-01-07              50.677604                          0.085309  0.836508
2019-01-08              48.878625                          0.131111  0.588138
2019-01-09              48.520088                          0.162324 -0.065941

            ROC_10_Normalized  Close_lag3  Close_lag3_Normalized  Close_lag5
Date
2018-12-11           0.884760  118.480000               0.854196  119.600000
2018-12-12           0.739157  119.170000               0.887187  121.180000
2018-12-13           0.700185  119.600000               0.883649  120.740000
2018-12-14           0.672196  121.180000               0.898087  120.720000
2018-12-17           0.702885  120.740000               0.785757  121.320000
2018-12-18           0.683267  120.720000               0.753673  120.020000
2018-12-19           0.594393  121.320000               0.796074  120.040000
2018-12-20           0.409397  120.020000               0.678652  121.050000
2018-12-21           0.366215  120.040000               0.749525  121.510000
2018-12-24           0.383694  121.050000               0.879947  122.150000
2018-12-26           0.188563  121.510000               0.899384  123.540000
2018-12-27           0.284868  122.150000               0.901450  122.110000
2018-12-28           0.487989  123.540000               0.956843  121.750000
2018-12-31           0.480257  122.110000               0.809991  121.430000
2019-01-02           0.450596  121.750000               0.760020  121.240000
2019-01-03           0.743794  121.430000               0.664462  122.014000
2019-01-04           0.006328  121.240000               0.585994  121.632500
2019-01-07           0.031397  121.473333               0.616173  121.473333
2019-01-08           0.034103  121.335000               0.555809  121.335000
2019-01-09           0.027165  121.240000               0.508268  121.240000

[20 rows x 25 columns]
Current feature:  Close_lag5
transform:  ['Normalized', 20]
pass params [20]

f9
fname:  ChaikinADOSC
params:  [4, 10]
Current feature:  ChaikinADOSC_f4_s10
transform:  ['Normalized', 20]
pass params [20]

In [21]:
feat_df = transf.normalizer(feat_df, 'Volume', 50)

In [22]:
feat_df.tail(2)

,Open,High,Low,Close,AdjClose,Volume,gainAhead,beLong,PPO_f2_s5,PPO_f2_s5_Normalized,...,UltOsc_t110_t220_t330_Normalized,ROC_10,ROC_10_Normalized,Close_lag3,Close_lag3_Normalized,Close_lag5,Close_lag5_Normalized,ChaikinADOSC_f4_s10,ChaikinADOSC_f4_s10_Normalized,Volume_Normalized
Date,,,,,,,,,,,,,,,,,,,,,
2019-01-08,121.69,121.94,121.39,121.43,121.1547,7737103.0,-0.001565,-1,-0.495925,0.131362,...,0.131111,0.588138,0.034103,121.335,0.555809,121.335,0.519726,8.927207e+06,0.991828,0.419745
2019-01-09,121.26,121.43,120.80,121.24,120.9700,9349245.0,0.000000,-1,-0.556494,0.128818,...,0.162324,-0.065941,0.027165,121.240,0.508268,121.240,0.462394,7.606878e+06,0.896219,0.567183

In [23]:
col_vals = [k for k,v in feature_dict.items() if v == 'Drop']
to_drop = ['Open','High','Low', 'gainAhead', 'Close', 'Volume', 'AdjClose', 'beLong']
for x in to_drop:
    col_vals.append(x)
model_data = dSet.drop_columns(feat_df, col_vals)

In [24]:
model_data.tail(2)

,PPO_f2_s5_Normalized,RSI_2_Normalized,UltOsc_t110_t220_t330_Normalized,ROC_10_Normalized,Close_lag3_Normalized,Close_lag5_Normalized,ChaikinADOSC_f4_s10_Normalized,Volume_Normalized
Date,,,,,,,,
2019-01-08,0.131362,0.144010,0.131111,0.034103,0.555809,0.519726,0.991828,0.419745
2019-01-09,0.128818,0.180108,0.162324,0.027165,0.508268,0.462394,0.896219,0.567183

In [25]:
# Retrieve model
best_model_name = system_dict["best_model"]
file_title = "fit-model-" + best_model_name + "-IS-" + system_name + ".sav"
file_name = os.path.join(system_directory, file_title)
model = pickle.load(open(file_name, 'rb'))

In [26]:
# get last row of data
lastRow = model_data.shape[0]
model_end_date = model_data.index[lastRow-1]
print(model_end_date)

2019-01-09 00:00:00

In [27]:
# Make prediction
predict_data = model_data.iloc[lastRow-1]
dX = np.zeros_like(predict_data)
dX = predict_data.values
dX = dX.reshape(1, -1)
dX

array([[ 0.12881817,  0.18010848,  0.1623241 ,  0.02716469,  0.50826764,
         0.46239442,  0.896219  ,  0.56718326]])

In [28]:
# get prediction
y_validate = []
y_validate = model.predict(dX)
y_validate

array([1])

In [29]:
y_validate[0]

1

In [30]:
# Get shadow trades
filename = "OOS_Equity_daybyday_" + system_name + ".csv"
path = system_directory+ "\\" + filename
shadow_trades = pd.read_csv(path)

In [31]:
shadow_trades.tail(2)

          Date  signal  gainAhead   Close
86  2019-01-07       1  -0.002628  121.75
87  2019-01-08       1   0.000000  121.43

In [32]:
model_data.tail(3)

,PPO_f2_s5_Normalized,RSI_2_Normalized,UltOsc_t110_t220_t330_Normalized,ROC_10_Normalized,Close_lag3_Normalized,Close_lag5_Normalized,ChaikinADOSC_f4_s10_Normalized,Volume_Normalized
Date,,,,,,,,
2019-01-07,0.201166,0.077053,0.085309,0.031397,0.616173,0.564294,0.999964,0.479504
2019-01-08,0.131362,0.144010,0.131111,0.034103,0.555809,0.519726,0.991828,0.419745
2019-01-09,0.128818,0.180108,0.162324,0.027165,0.508268,0.462394,0.896219,0.567183

In [33]:
feat_df.Close[lastRow-1]

121.23999999999999

#### Update shadow trades to start
- Current date, signal for date, Close for date, gainAhead for previous Day

In [34]:
new_st_df = shadow_trades.append({'Date' : tradeDate , 'signal' : y_validate[0], 'gainAhead' : 0.000, 'Close' : feat_df.Close[lastRow-1] } , ignore_index=True)

In [35]:
new_st_df.tail(3)

          Date  signal  gainAhead   Close
86  2019-01-07       1  -0.002628  121.75
87  2019-01-08       1   0.000000  121.43
88  2019-01-09       1   0.000000  121.24

In [36]:
new_st_df['gainAhead'] = ct.gainAhead(new_st_df.Close)

In [37]:
new_st_df.tail(3)

          Date  signal  gainAhead   Close
86  2019-01-07       1  -0.002628  121.75
87  2019-01-08       1  -0.001565  121.43
88  2019-01-09       1   0.000000  121.24

#### Save updated shadow trades

In [38]:
#print(df_to_save)
filename = "OOS_Equity_daybyday_" + system_name + ".csv"
new_st_df.to_csv(system_directory+ "\\" + filename, encoding='utf-8', index=False)

#### Load TMS - Part 1

In [39]:
filename = "TMS_Part1_daybyday_" + system_name + ".csv"
path = system_directory+ "\\" + filename
tms1 = pd.read_csv(path)
tms1.tail(3)

          Date  signal  gainAhead   Close     safef       CAR25
85  2019-01-04       1  -0.002948  122.11  4.106390  238.459453
86  2019-01-07       1  -0.002628  121.75  4.000108  182.193789
87  2019-01-08       1   0.000000  121.43  4.001145  199.063846

In [40]:
# Update TMS-Part 1 data with latest date
sst = tms1.append({'Date' : tradeDate , 'signal' : y_validate[0], 'gainAhead' : 0, 'Close' :  feat_df.Close[lastRow-1]} , ignore_index=True)
sst.tail(3)

          Date  signal  gainAhead   Close     safef       CAR25
86  2019-01-07       1  -0.002628  121.75  4.000108  182.193789
87  2019-01-08       1   0.000000  121.43  4.001145  199.063846
88  2019-01-09       1   0.000000  121.24       NaN         NaN

In [41]:
# Update with gainAhead
end = sst.index[-2]
sst.iloc[end,sst.columns.get_loc('gainAhead')] = new_st_df.iloc[end,new_st_df.columns.get_loc('gainAhead')]
sst.tail(3)

          Date  signal  gainAhead   Close     safef       CAR25
86  2019-01-07       1  -0.002628  121.75  4.000108  182.193789
87  2019-01-08       1  -0.001565  121.43  4.001145  199.063846
88  2019-01-09       1   0.000000  121.24       NaN         NaN

#### Update TMS-Part 1 with safe-f, CAR25

In [42]:
nrows = sst.shape[0]
# sst = sst.set_index(pd.DatetimeIndex(sst['Date']))
start = sst.index[0]
end = sst.index[-1]

iStart = sst.index.get_loc(end)-1
iEnd = sst.index.get_loc(end)

In [43]:
# retrieve tms_dict
file_name = 'tms_dict.json'
file_path = os.path.join(system_directory, file_name)
tms_dict = load_json(file_path)

forecastHorizon = tms_dict["forecastHorizon"]
initialEquity = tms_dict["initialEquity"]
ddTolerance = tms_dict["ddTolerance"]
tailRiskPct = tms_dict["tailRiskPct"]
windowLength = tms_dict["windowLength"]
nCurves = tms_dict["nCurves"]
updateInterval = tms_dict["updateInterval"]

years_in_forecast = forecastHorizon / 252.0

printDetails = False

In [44]:
# Calculate safe-f, CAR25
for i in range(iStart, iEnd+1, updateInterval):
    if printDetails: 
        print ("\nDate: ", dt.datetime.strftime(sst.index[i], '%Y-%m-%d'))
        print ("beLong: ", sst.signal[i])
        print ("gain Ahead: {0:.4f}".format(sst.gainAhead[i]))

#  Initialize variables
    curves = np.zeros(nCurves)
    numberDraws = np.zeros(nCurves)
    TWR = np.zeros(nCurves)
    maxDD = np.zeros(nCurves)
    
    fraction = 1.00
    dd95 = 2 * ddTolerance
    
    while (abs(dd95-ddTolerance)>0.03):
        #  Generate nCurve equity curves
        if printDetails: 
            print  ("    Fraction {0:.2f}".format(fraction))
#    
        for nc in range(nCurves):
            #print ("working on curve ", nc)
            equity = initialEquity
            maxEquity = equity
            drawdown = 0
            maxDrawdown = 0
            horizonSoFar = 0
            nd = 0
            while (horizonSoFar < forecastHorizon):
                j = np.random.randint(0,windowLength)
        #        print j
                nd = nd + 1
                weightJ = 1.00 - j/windowLength
        #        print weightJ
                horizonSoFar = horizonSoFar + weightJ
                signalJ = sst.signal[i-j]
                if signalJ > 0:
                    tradeJ = sst.gainAhead[i-j] * weightJ
                else:
                    tradeJ = 0.0
                thisTrade = fraction * tradeJ * equity    
                equity = equity + thisTrade
                maxEquity = max(equity,maxEquity)
                drawdown = (maxEquity-equity)/maxEquity
                maxDrawdown = max(drawdown,maxDrawdown)
    #        print "equity, maxDD, ndraws:", equity, maxDrawdown, nd        
            TWR[nc] = equity
            maxDD[nc] = maxDrawdown
            numberDraws[nc] = nd
    
        #  Find the drawdown at the tailLimit-th percentile        
        dd95 = stats.scoreatpercentile(maxDD,tailRiskPct)
        if printDetails: 
            print ('  DD {0}: {1:.3f} '.format(tailRiskPct, dd95))
        fraction = fraction * ddTolerance / dd95
        TWR25 = stats.scoreatpercentile(TWR,25)        
        CAR25 = 100*(((TWR25/initialEquity) ** (1.0/years_in_forecast))-1.0)
    if printDetails: 
        print ('Fraction: {0:.2f}'.format(fraction))
        print ('CAR25: {0:.2f}'.format(CAR25))
    sst.iloc[i,sst.columns.get_loc('safef')] = fraction
    sst.iloc[i,sst.columns.get_loc('CAR25')] = CAR25
    #sst.loc[i,'CAR25'] = CAR25

In [45]:
sst.tail(3)

          Date  signal  gainAhead   Close     safef       CAR25
86  2019-01-07       1  -0.002628  121.75  4.000108  182.193789
87  2019-01-08       1  -0.001565  121.43  4.081776  180.853109
88  2019-01-09       1   0.000000  121.24  4.268551  175.960196

#### Save updated shadow trades

In [46]:
df_to_save = sst.copy()
#df_to_save.reset_index(level=df_to_save.index.names, inplace=True)
filename = "TMS_Part1_daybyday_" + system_name + ".csv"
df_to_save.to_csv(system_directory+ "\\" + filename, encoding='utf-8', index=False)

In [47]:
df_to_save.tail(3)

          Date  signal  gainAhead   Close     safef       CAR25
86  2019-01-07       1  -0.002628  121.75  4.000108  182.193789
87  2019-01-08       1  -0.001565  121.43  4.081776  180.853109
88  2019-01-09       1   0.000000  121.24  4.268551  175.960196

#### Now go to TMS Part 2

In [48]:
filename = "TMS_Part2_daybyday_" + system_name + ".csv"
path = system_directory+ "\\" + filename
tms2 = pd.read_csv(path)
tms2.tail(3)

,Date,signal,gainAhead,Close,safef,CAR25,trade,fract,equity,maxEquity,drawdown,maxDD,trade_decision
85,2019-01-04,1,-0.002948,122.11,4.513595,267.463166,-2105.315717,4.513595,147106.945720,150881.27067,0.025015,0.104042,Long
86,2019-01-07,1,-0.002628,121.75,4.299572,234.236298,-1745.166098,4.299572,145361.779622,150881.27067,0.036582,0.104042,Long
87,2019-01-08,1,0.000000,121.43,4.001145,199.063846,NaN,NaN,NaN,NaN,NaN,NaN,Long

#### Append last day  form TMS Part 1 to TMS Part 2

In [49]:
tms21 = tms2.copy()
sst1 = sst.copy()
#sst1.reset_index(level=sst1.index.names, inplace=True)
tms21.loc[sst1.index[-1]] = sst1.iloc[-1]

In [50]:
tms21.tail(3)

,Date,signal,gainAhead,Close,safef,CAR25,trade,fract,equity,maxEquity,drawdown,maxDD,trade_decision
86,2019-01-07,1,-0.002628,121.75,4.299572,234.236298,-1745.166098,4.299572,145361.779622,150881.27067,0.036582,0.104042,Long
87,2019-01-08,1,0.000000,121.43,4.001145,199.063846,NaN,NaN,NaN,NaN,NaN,NaN,Long
88,2019-01-09,1,0.000000,121.24,4.268551,175.960196,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
nrows = tms21.shape[0]
start = tms21.index[0]
end = tms21.index[-1]

iStart = tms21.index.get_loc(end)-1
iEnd = tms21.index.get_loc(end)

In [52]:
iStart

87

In [53]:
# Update gainAhead
tms21.iloc[iStart,tms21.columns.get_loc('gainAhead')] = sst1.iloc[iStart,sst1.columns.get_loc('gainAhead')]

In [54]:
tms21.tail(3)

,Date,signal,gainAhead,Close,safef,CAR25,trade,fract,equity,maxEquity,drawdown,maxDD,trade_decision
86,2019-01-07,1,-0.002628,121.75,4.299572,234.236298,-1745.166098,4.299572,145361.779622,150881.27067,0.036582,0.104042,Long
87,2019-01-08,1,-0.001565,121.43,4.001145,199.063846,NaN,NaN,NaN,NaN,NaN,NaN,Long
88,2019-01-09,1,0.000000,121.24,4.268551,175.960196,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
# Update trade_decision with current date decision
tms21.iloc[iEnd,tms21.columns.get_loc('trade_decision')] = 'Long'

In [56]:
tms21.tail(3)

,Date,signal,gainAhead,Close,safef,CAR25,trade,fract,equity,maxEquity,drawdown,maxDD,trade_decision
86,2019-01-07,1,-0.002628,121.75,4.299572,234.236298,-1745.166098,4.299572,145361.779622,150881.27067,0.036582,0.104042,Long
87,2019-01-08,1,-0.001565,121.43,4.001145,199.063846,NaN,NaN,NaN,NaN,NaN,NaN,Long
88,2019-01-09,1,0.000000,121.24,4.268551,175.960196,NaN,NaN,NaN,NaN,NaN,NaN,Long

In [57]:
for i in range(iStart, iEnd):
    if (tms21.trade_decision[i] == 'Long'):
        tms21.iloc[i,tms21.columns.get_loc('trade')] = tms21.iloc[i-1,tms21.columns.get_loc('fract')] * tms21.iloc[i-1,tms21.columns.get_loc('equity')] * tms21.iloc[i,tms21.columns.get_loc('gainAhead')]
    elif (tms21.signal[i] > 0):
        tms21.iloc[i,tms21.columns.get_loc('trade')] = tms21.iloc[i-1,tms21.columns.get_loc('fract')] * tms21.iloc[i-1,tms21.columns.get_loc('equity')] * tms21.iloc[i,tms21.columns.get_loc('gainAhead')]
    else:
        tms21.iloc[i,tms21.columns.get_loc('trade')] = 0.0
        
    tms21.iloc[i,tms21.columns.get_loc('fract')] = tms21.iloc[i,tms21.columns.get_loc('safef')]
    
    tms21.iloc[i,tms21.columns.get_loc('equity')] = tms21.iloc[i-1,tms21.columns.get_loc('equity')] + tms21.iloc[i,tms21.columns.get_loc('trade')]
    tms21.iloc[i,tms21.columns.get_loc('maxEquity')] = max(tms21.iloc[i,tms21.columns.get_loc('equity')],tms21.iloc[i-1,tms21.columns.get_loc('maxEquity')])
    tms21.iloc[i,tms21.columns.get_loc('drawdown')] = (tms21.iloc[i,tms21.columns.get_loc('maxEquity')] - tms21.iloc[i,tms21.columns.get_loc('equity')]) / tms21.iloc[i,tms21.columns.get_loc('maxEquity')]
    tms21.iloc[i,tms21.columns.get_loc('maxDD')] =  max(tms21.iloc[i,tms21.columns.get_loc('drawdown')],tms21.iloc[i-1,tms21.columns.get_loc('maxDD')])
    tms21.iloc[i,tms21.columns.get_loc('fract')] = tms21.iloc[i,tms21.columns.get_loc('safef')]

In [58]:
tms21.tail(3)

,Date,signal,gainAhead,Close,safef,CAR25,trade,fract,equity,maxEquity,drawdown,maxDD,trade_decision
86,2019-01-07,1,-0.002628,121.75,4.299572,234.236298,-1745.166098,4.299572,145361.779622,150881.27067,0.036582,0.104042,Long
87,2019-01-08,1,-0.001565,121.43,4.001145,199.063846,-977.919468,4.001145,144383.860153,150881.27067,0.043063,0.104042,Long
88,2019-01-09,1,0.000000,121.24,4.268551,175.960196,NaN,NaN,NaN,NaN,NaN,NaN,Long

#### Save updated TMS Part 2

In [59]:
df_to_save = tms21.copy()
#df_to_save.reset_index(level=df_to_save.index.names, inplace=True)
filename = "TMS_Part2_daybyday_" + system_name + ".csv"
df_to_save.to_csv(system_directory+ "\\" + filename, encoding='utf-8', index=False)

#### Save system_dict

In [60]:
tradeDate

'2019-01-09'

In [61]:
system_dict

{'best_model': 'SVM',
 'direction': 'Long',
 'is_oos_ratio': 4,
 'issue': 'TLT',
 'oos_months': 4,
 'pivot_date': '2019-01-08',
 'segments': 1,
 'system_name': 'TLT-Long-system-7045-V1',
 'ver_num': 1}

In [62]:
system_dict['pivot_date']=tradeDate
system_dict

{'best_model': 'SVM',
 'direction': 'Long',
 'is_oos_ratio': 4,
 'issue': 'TLT',
 'oos_months': 4,
 'pivot_date': '2019-01-09',
 'segments': 1,
 'system_name': 'TLT-Long-system-7045-V1',
 'ver_num': 1}

In [63]:
save_json('system_dict.json', system_dict)

## End of day completed, 2019-01-09
Trade decision: Long

## Start next day, 2019-01-10